#!/usr/bin/env python

"""
A tool to delete images.

Examples:

    ./gg-image-delete -i id <-- removes server by id

    ./gg-image-delete -n name <-- removes server by name
"""

import re
import sys
import getopt
from GoGridManager import GoGridManager
from GoGridClient import GoGridException

if __name__ == "__main__":
    account = "default"
    id = name = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "i:n:")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)

    for o, a in opts:
        if o == "-i":
            id = a
        elif o == "-n":
            name = a

    if name is None and id is None:
        print "You should specifiy either id or name!"
        sys.exit(1)

    manager = GoGridManager(account=account)

    image = manager.delete_image(id, name, None)

    print image
