#!/usr/bin/env python

"""A tool to list available images, doesn't need any arguments"""

import sys

from GoGridManager import GoGridManager
from GoGridClient import Error403

if __name__ == "__main__":
    manager = GoGridManager()

    try:
        images = manager.get_images()
    except (Error403,), e:
        print e
        sys.exit(2)

    for image in images:
        print image
