#!/usr/bin/env python

"""A tool to list available images."""

import getopt
import sys

from GoGridManager import GoGridManager
from GoGridClient import Error403

if __name__ == "__main__":
    account = "default"
    show_all = False

    try:
        opts, args = getopt.getopt(sys.argv[1:], "ap:")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)

    for o, a in opts:
        if o == "-p":
            account = a
        if o == "-a":
            show_all = True

    manager = GoGridManager(account=account)

    try:
        images = manager.get_images()
    except (Error403,), e:
        print e
        sys.exit(2)

    if show_all is False:
        images = filter(lambda x: x.state != "Trash", images)

    for image in images:
        print image
