#!/usr/bin/env python

import sys
import getopt
from GoGridManager import GoGridManager

def usage():
    print "%s -n name -s server [ -d descr ]" % sys.argv[0]
    print

if __name__ == "__main__":
    account = "default"
    name = server = descr = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "a:n:s:d:")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)

    for o, a in opts:
        if o == "-a":
            account = a
        elif o == "-n":
            name = a
        elif o == "-s":
            server = a
        elif o == "-d":
            descr = a

    manager = GoGridManager(account=account)

    if (name or server) is None:
        usage()
        sys.exit(2)

    print manager.save_image(name, server, descr)
    
