#!/bin/sh

# Shortcut command for lookups
#
# Examples:
#    ./gg-lookup server.type <-- lists available server types
#
#    ./gg-lookup lookups <-- lists all the lookup variables
#

gg_home=`dirname $0`

${gg_home}/gg-raw "/common/lookup/list" "lookup=$1"
