#!/usr/bin/env python

import getopt
import sys

from GoGridManager import GoGridManager

if __name__ == "__main__":
    account = "default"

    try:
        opts, args = getopt.getopt(sys.argv[1:], "a:")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)


    for o, a in opts:
        if o == "-a":
            account = a
            
    manager = GoGridManager(account=account)

    passwords = manager.get_passwords() 

    print "%5s %20s %20s %20s" % ("id", "username",  "password", "server")
    for password in passwords:
        print "%5s %20s %20s %20s" % (password.id, password.username, password.password, password.server.ip.ip)
