#!/usr/bin/env python

import sys

from GoGridManager import GoGridManager

if __name__ == "__main__":
    manager = GoGridManager()

    passwords = manager.get_passwords() 

    print "%5s %20s %20s %20s" % ("id", "username",  "password", "server")
    for password in passwords:
        print "%5s %20s %20s %20s" % (password.id, password.username, password.password, password.server.ip.ip)
