#!/usr/bin/env python

"""A tool to perform a raw query to GoGrid API

Example:

    ./gg-raw "common/lookup/list" lookup=ip.state

"""

import sys

from GoGridClient import GoGridClient

def usage():
    print "%s request key1=val1 key2=val2 ... keyN=valN" % sys.argv[0]
    print

if __name__ == "__main__":
    client = GoGridClient()

    if len(sys.argv) < 2:
        usage()
        sys.exit(2)

    request = sys.argv[1]
    param_dict = {}

    for param in sys.argv[2:]:
        k, v = param.split("=")

        param_dict[k] = v

    print client.sendAPIRequest(request, param_dict)
