#!/usr/bin/env python

"""A script to add a new server

Example:

    ./gg-server-add -n somename -i centos51_64_apache -r 512MB -a som.e.add.r
   
You can omit IP address of the machine (i.e. don't specify -a) and it will pick
on of the available public IPs in state Unassigned.
"""

import sys
import getopt
from random import choice
from GoGridManager import GoGridManager

def usage():
    print "%s -n name -i image -r ram -a ip_addr [ -d descr ]" % sys.argv[0]
    print

if __name__ == "__main__":
    account = "default"
    name = image = ram = ip = descr = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "n:i:p:r:sa:d:")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)
    
    for o, a in opts:
        if o == "-p":
            account = a
        elif o == "-n":
            name = a
        elif o == "-i":
            image = a
        elif o == "-r":
            ram = a
        elif o == "-a":
            ip = a
        elif o == "-d":
            descr = a

    manager = GoGridManager(account=account)

    if ip is None:
        ip = choice(manager.get_ips(type='Public', state='Unassigned')).ip

    if (name and image and ram and ip) is None:
        usage()
        sys.exit(2)

    server = manager.add_server(name, image, ram, ip, descr)
    print "%s %s" % (server.name, server.ip.ip)
