#!/usr/bin/env python

"""A tool to list currently available servers.

Example:

    ./gg-server-list <-- shows a list of servers
     
    ./gg-server-list -H <-- shows a list of servers and appends header to the output

Yeah, that's simple"""

import sys
import getopt

from GoGridManager import GoGridManager
from GoGridClient import Error403

if __name__ == "__main__":
    account = "default"
    show_headers = False
    show_description = False

    try:
        opts, args = getopt.getopt(sys.argv[1:], "p:Hd")
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(2)

    for o, a in opts:
        if o == "-p":
            account = a
        elif o == "-H":
            show_headers = True
        elif o == "-d":
            show_description = True

    manager = GoGridManager(account=account)

    try:
        servers = manager.get_servers()
    except (Error403,), e:
        print e
        sys.exit(2)

    if show_headers:
        if show_description:
            desc_hdr = 'description'
        else:
            desc_hdr = ''
        print "%6s %12s %20s %10s   %s" % ("id", "name", "ip", "state", desc_hdr)

    for server in servers:
        if server.isSandbox:
            server.name += '<'
        if show_description:
            desc = server.descr
        else:
            desc = ''
        print "%6s %12s %20s %10s   %s" % (server.id, server.name, server.ip.ip, server.state, desc)
